### ISSUE TITLE
Facing issue with getting release files

### ISSUE THREAD

**Issue by strange2x** [Stuyk/altv-pkg#10]
Hey,

When I tried using the latest version of altv-pkg and I tried installing the latest binaries, I'm getting the following issues:

> $ altv-pkg release
/usr/bin/env: ‘node\r’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines

Platform: Linux [Archlinux]
Node Version: 18

Thanks.

**Comment by Stuyk** [comment]
Should be resolved in 2.0.3 now. Re-open this if you still run into the problem. @strange2x
